### ISSUE TITLE
load_path修改建议

### ISSUE THREAD

**Issue by kosakarin** [FLAG250/hoshino-plugin-pjsk#1]
`33  load_path = "C:\\Users\\Administrator\\Desktop\\haru-bot-setup\\hoshino\\modules\\pjsk"     #请按个人插件存放位置更改绝对路径`
此处直接使用 `load_path = os.path.dirname(__file__)` 可以直接自动获取该.py文件所在文件夹绝对路径，需要`import os` 你的源码中已经import了，所以无需额外的修改

**Comment by FLAG250** [comment]
> 

好的 多谢指出！
