### ISSUE TITLE
为何一直回复uid格式错误

### ISSUE THREAD

**Issue by xiaoxianyu233** [FLAG250/hoshino-plugin-pjsk#4]
![image](https://user-images.githubusercontent.com/69450441/179789246-1e602c66-19de-4a07-ac70-23869c966e3d.png)

**Comment by xiaoxianyu233** [comment]
草，为什么一定要有一个+

**Comment by xiaoxianyu233** [comment]
> 不用+号的 如果刚开始使用的话 建议现在account.json里面输个自己的qq账号和uid） 很多大问题没排 但是不影响使用 等后面开新功能一起优化了

确实，辛苦力

**Comment by kosakarin** [comment]
> 不用+号的 如果刚开始使用的话 建议现在account.json里面输个自己的qq账号和uid） 很多大问题没排 但是不影响使用 等后面开新功能一起优化了

问题我感觉出在这里
![image](https://user-images.githubusercontent.com/91523573/179891173-eda0e3d0-9e58-4406-9e68-15cfa05ce86c.png)
不是很清楚这里为什么B不能等于0
如果单纯的想在for循环执行结束后去做什么事情的话可以直接用
`for:`
`else:`
来操作，比如改为
![image](https://user-images.githubusercontent.com/91523573/179891341-4a29f09c-81f2-495f-ad0e-3c494d6dd199.png)
这样就可以在.json文件初始为[]时正常写入绑定信息了
